language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_script:
  - composer require satooshi/php-coveralls:dev-master

script:
  - phpunit --colors ./tests
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml ./tests

after_script:
  - php vendor/bin/coveralls -v